import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true}),url='file://'+process.cwd()+'/index.html',errors=[];
await mkdir('artifacts/adventures',{recursive:true});
async function seed(page,{count=55,slots=[],inventory={},pending=[],balance=5}={}){await page.goto(url);await page.evaluate(s=>localStorage.setItem('75-magic-machine:v1',JSON.stringify(s)),{version:1,muted:true,inventory,history:[],energy:{balance,difficulty:'easy'},garden:{slots},world:{completedDraws:count,lastWitchDraw:count,seenOpponents:['bat','witch','rock','dragon'],pending}});await page.reload();}
async function hit(page){await page.waitForFunction(()=>!document.querySelector('#witch-target').hidden&&!document.querySelector('#witch-target').disabled);await page.locator('#witch-target').click();await page.waitForFunction(()=>!document.querySelector('.witch-shot'));}
try{
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push(e.message));
 await seed(page,{pending:[{kind:'event',id:'fairy',giftId:'cloud-dolphin'}],balance:2});await page.waitForSelector('#world-visitor[data-action=visiting]');assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('.visitor-bubble').count(),0);assert.equal(await page.locator('.visitor-energy-heart').count(),5);assert.equal(await page.locator('#power-count').textContent(),'7 / 10');await page.screenshot({path:'artifacts/adventures/fairy.png'});
 await seed(page,{pending:[{kind:'event',id:'mermaid',giftId:'cloud-dolphin'}]});await page.waitForSelector('#world-visitor[data-kind=mermaid][data-action=visiting]');assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('#collection-count').textContent(),'1');await page.screenshot({path:'artifacts/adventures/mermaid.png'});await page.reload();assert.equal(await page.locator('#collection-count').textContent(),'1');assert.equal(await page.locator('#world-visitor').isVisible(),false);
 // 金币不用 emoji，颜色固定为黄色。
 await seed(page);await page.evaluate(()=>{const natural=Math.random;let first=true;Math.random=()=>{if(first){first=false;return .65;}return natural();};});await page.locator('#weather').click();assert.equal(await page.locator('body').getAttribute('data-weather'),'coins');assert.equal(await page.locator('#weather-layer i').first().textContent(),'★');assert.equal(await page.locator('#weather-layer i').first().evaluate(el=>getComputedStyle(el).borderTopColor),'rgb(231, 151, 19)');await page.screenshot({path:'artifacts/adventures/coins.png'});
 // 多个已摆放守护者每件一次，妈妈护盾独立，攻击不超过一半；仅拥有不生效。
 const guards=['pretty-magic-wand','moon-blaster','super-dad','rainbow-dragon','winged-fairy-gem','loving-mom'];const inventory=Object.fromEntries(guards.map(id=>[id,1]));
 await seed(page,{slots:guards,inventory,pending:[{kind:'witch',opponent:'rock',hits:0,giftId:'cloud-dolphin'}]});await page.waitForSelector('#garden-broadcast[data-action=rising]');assert.match(await page.locator('#broadcast-message').textContent(),/石头怪/);await page.waitForTimeout(700);await page.screenshot({path:'artifacts/adventures/broadcast.png'});await page.waitForFunction(()=>document.querySelector('#witch-hit-count').textContent==='3 / 6');await page.waitForFunction(()=>document.getElementById('witch-stage').classList.contains('guardian-shield')); await page.waitForTimeout(1600);assert.equal(await page.locator('#witch-hit-count').textContent(),'3 / 6');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('75-magic-machine:v1')));assert.equal(saved.world.pending[0].assistHits,3);assert.equal(saved.world.pending[0].shieldUsed,true);assert.equal(new Set(saved.world.pending[0].usedGuardians).size,3);
 await page.reload();await page.waitForSelector('#witch-stage[data-action=ready]');await page.waitForTimeout(1700);assert.equal(await page.locator('#witch-hit-count').textContent(),'3 / 6');await hit(page);await hit(page);assert.equal(await page.locator('#witch-hit-count').textContent(),'5 / 6');await page.waitForTimeout(1400);assert.equal(await page.locator('#witch-hit-count').textContent(),'5 / 6');await hit(page);await page.waitForSelector('#witch-stage[data-action=won]');assert.equal(await page.locator('#collection-count').textContent(),'7');assert.match(await page.locator('#broadcast-message').textContent(),/安全/);await page.locator('#witch-continue').click();await page.reload();assert.equal(await page.locator('#collection-count').textContent(),'7');
 await seed(page,{inventory,pending:[{kind:'witch',opponent:'bat',hits:0,giftId:'cloud-dolphin'}]});await page.waitForSelector('#witch-stage[data-action=ready]');await page.waitForTimeout(1800);assert.equal(await page.locator('#witch-hit-count').textContent(),'0 / 3');
 // 大龙十格，五个攻击伙伴至多五次，后半段有明显形态/迷雾反馈。
 await seed(page,{slots:guards,inventory,pending:[{kind:'witch',opponent:'dragon',hits:0,giftId:'cloud-dolphin'}]});await page.waitForFunction(()=>document.querySelector('#witch-hit-count').textContent==='5 / 10');await page.waitForSelector('#witch-stage[data-phase=angry]');assert.equal(await page.locator('#witch-hit-stars span').count(),10);await page.screenshot({path:'artifacts/adventures/dragon.png'});for(let i=0;i<5;i++)await hit(page);await page.waitForSelector('#witch-stage[data-action=won]');await page.locator('#witch-continue').click();
 // 真正点击宝物：随机不重复、第三次组合惊喜，不额外发奖或扣能量。
 await seed(page,{slots:['super-dad'],inventory:{'super-dad':1}});const toy=page.locator('.garden-slot[data-slot="0"]');await toy.click();const first=await toy.getAttribute('data-reaction');assert.ok(first);await page.waitForTimeout(2500);await toy.click();assert.notEqual(await toy.getAttribute('data-reaction'),first);await page.waitForTimeout(2500);await toy.click();assert.equal(await toy.getAttribute('data-surprise'),'true');assert.match(await toy.locator('.play-caption').textContent(),/三连/);assert.equal(await page.locator('#collection-count').textContent(),'1');assert.equal(await page.locator('#power-count').textContent(),'5 / 10');await page.screenshot({path:'artifacts/adventures/poop-surprise.png'});
 const mobile=await browser.newPage({viewport:{width:320,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});mobile.on('pageerror',e=>errors.push(e.message));await seed(mobile,{pending:[{kind:'witch',opponent:'dragon',hits:9,giftId:'cloud-dolphin'}]});await mobile.waitForSelector('#witch-stage[data-action=ready]');assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:'artifacts/adventures/mobile-dragon.png'});await mobile.locator('#witch-target').tap();await mobile.waitForSelector('#witch-stage[data-action=won]');assert.equal(await mobile.locator('#collection-count').textContent(),'1');
 for(const kind of ['broadcast','rock-arrive','dragon-arrive','mermaid','guardian-shield']){const peak=await page.evaluate(async kind=>{const ctx=new OfflineAudioContext(1,44100*4,44100),s=new MagicAudio(()=>false);s.setup(ctx);s.ready=()=>true;s.encounter(kind);let peak=0;for(const v of(await ctx.startRendering()).getChannelData(0))peak=Math.max(peak,Math.abs(v));return peak;},kind);assert.ok(peak>.01&&peak<.98);}
 assert.deepEqual(errors,[]);console.log('通过：黄色金币、场景仙子/飞行爱心、美人鱼赠礼幂等、地面广播、3/6/10血量、多伙伴/一半助攻/妈妈护盾/刷新、第三次宝物惊喜、手机与新音效');
}catch(error){console.log('浏览器错误', errors);for(const context of browser.contexts()) for(const page of context.pages()) {console.log(await page.evaluate(()=>({stage:document.getElementById('witch-stage')?.outerHTML.slice(0,120),feed:document.getElementById('witch-feedback')?.textContent,pending:JSON.parse(localStorage.getItem('75-magic-machine:v1'))?.world?.pending})));await page.screenshot({path:'artifacts/adventures/failure.png'});}throw error;}finally{await browser.close();}
