import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});const url='file://'+process.cwd()+'/index.html',key='75-magic-machine:v1';
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base={version:2,muted:true,history:[],inventory:{'cloud-dolphin':1},energy:{balance:7},world:{completedDraws:2,pending:[]},garden:{slots:[],workshop:{active:'ocean-party'}}};
 const seed=async save=>{await page.goto(url);await page.evaluate(({key,save})=>localStorage.setItem(key,JSON.stringify(save)),{key,save});await page.reload();};const snapshot=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
 await seed(base);assert.ok(await page.locator('#craft-goal').isVisible());assert.ok(await page.locator('#garden-wish').isHidden());assert.match(await page.locator('#craft-goal-title').textContent(),/海豚泡泡池/);assert.equal(await page.locator('.goal-partner.found').count(),1);assert.equal(await page.locator('.goal-partner.wanted').count(),1);assert.match(await page.locator('#craft-goal-progress').textContent(),/1\/2/);const target=await page.locator('.goal-partner.wanted').getAttribute('data-goal-treasure');assert.ok(!(await snapshot()).inventory[target]);assert.match(await page.locator('.goal-partner.wanted b').textContent(),/还想抽到/);
 assert.equal(await page.locator('#craft-goal-action').count(),0);assert.equal(await page.locator('.draw-button').count(),1);assert.equal(await page.locator('#craft-goal').evaluate(el=>el.parentElement.id),'window');await page.locator('#draw').click();await page.waitForSelector('#machine[data-state=result]');assert.equal((await snapshot()).world.completedDraws,3);assert.ok(await page.locator('#craft-goal').isVisible());assert.equal((await snapshot()).garden.workshop.active,'ocean-party');await page.reload();assert.match(await page.locator('#craft-goal-title').textContent(),/海豚泡泡池/);
 await seed({...base,inventory:{'cloud-dolphin':1,'whale-cup':1}});assert.match(await page.locator('#craft-task-badge').textContent(),/可合成/);await page.locator('#workshop-open').click();assert.equal(await page.locator('#machine').getAttribute('data-mode'),'craft');assert.deepEqual((await snapshot()).garden.workshop.tray,['cloud-dolphin','whale-cup']);assert.equal((await snapshot()).world.completedDraws,2);assert.equal((await snapshot()).energy.balance,7);
 assert.ok(await page.locator('#draw').isVisible());await page.locator('#wish-swap').click();assert.notEqual((await snapshot()).garden.workshop.active,'ocean-party');await page.locator('#draw').click();await page.waitForSelector('#machine[data-state=result]');assert.equal(await page.locator('#machine').getAttribute('data-mode'),null);assert.equal((await snapshot()).world.completedDraws,3);await page.reload();assert.notEqual((await snapshot()).garden.workshop.active,'ocean-party');
 await mkdir('artifacts/workshop',{recursive:true});for(const width of [1280,900,375,320]){await page.setViewportSize({width,height:900});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`artifacts/workshop/goal-${width}.png`});assert.ok(await page.locator('body').evaluate(el=>el.scrollWidth<=innerWidth));const rect=await page.locator('#craft-goal').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=width+.1);}
 await page.setViewportSize({width:1280,height:900});await seed({...base,inventory:{'little-alarm':1},garden:{slots:[],workshop:{active:'forest-concert'}}});await page.locator('#workshop-open').click();await page.locator('#wish-invite').click();assert.deepEqual((await snapshot()).garden.workshop.tray,[null,'little-alarm']);assert.equal(await page.locator('[data-tray="1"] .slot-preview').count(),0);
 await page.setViewportSize({width:1280,height:900});await seed({...base,world:{completedDraws:10,pending:[{kind:'upgrade',level:'rainbow'}]}});await page.locator('#workshop-open').click();assert.ok(await page.locator('#garden-wish').isHidden());await page.keyboard.press('Space');await page.waitForSelector('#world-dialog.acted');assert.ok(await page.locator('#craft-goal').isHidden());assert.equal((await snapshot()).world.completedDraws,10);assert.equal((await snapshot()).energy.balance,7);await page.locator('#continue-world').click();assert.deepEqual(errors,[]);
 console.log('Goals: visible during lottery, explicit wanted/owned partners, progress and persistence, one main draw button in both modes, ready invitation without cost, goal switching, mobile and queued upgrade priority.');
}finally{await browser.close();}
