import assert from 'node:assert/strict';import{mkdir}from'node:fs/promises';
const{chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});const key='75-magic-machine:v1',url='file://'+process.cwd()+'/index.html';
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base={version:2,muted:true,history:[],inventory:{'cloud-dolphin':1,'whale-cup':1},energy:{balance:7},world:{completedDraws:40,pending:[],seenOpponents:['bat','witch','rock','dragon'],seenEvents:['fairy','ghost','courier','mermaid']},garden:{slots:['cloud-dolphin'],discovered:['forest-concert','starlight-jewels'],workshop:{active:'ocean-party',tray:['cloud-dolphin','whale-cup']}}};
 const seed=async save=>{await page.goto(url);await page.evaluate(({key,save})=>localStorage.setItem(key,JSON.stringify(save)),{key,save});await page.reload();};const snapshot=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
 async function capture(){await page.evaluate(()=>{const sync=MagicWorkshop.prototype.sync;MagicWorkshop.prototype.sync=function(...args){window.workshop=this;return sync.apply(this,args);};});await page.locator('#workshop-open').click();}
 async function hit(){await page.waitForFunction(()=>{const t=document.getElementById('witch-target');return !t.hidden&&!t.disabled;});await page.locator('#witch-target').click();await page.waitForTimeout(520);}
 async function win(){while((await snapshot()).world.pending.length){await hit();}await page.locator('#witch-continue').click();await page.waitForFunction(()=>!document.body.classList.contains('world-busy'));}
 // Physical machine modes, real staged fusion, no draw/energy/ingredients consumed; Space always draws.
 await seed({...base,world:{completedDraws:2,pending:[]},garden:{slots:['cloud-dolphin'],workshop:base.garden.workshop}});await page.locator('#workshop-open').click();assert.equal(await page.locator('#garden-wish').evaluate(el=>el.parentElement.id),'window');await page.locator('#wish-action').click();await page.waitForSelector('#garden-wish[data-phase=fusion]');const before=await snapshot();await page.keyboard.press('Space');assert.equal((await snapshot()).world.completedDraws,2);await page.waitForSelector('#workshop-result:not([hidden])');await page.waitForSelector('#garden-story-stage:not([hidden])');await page.waitForFunction(()=>document.getElementById('garden-story-stage').hidden);assert.equal((await snapshot()).world.completedDraws,2);assert.deepEqual((await snapshot()).inventory,before.inventory);await page.locator('#workshop-open').focus();await page.keyboard.press('Space');await page.waitForSelector('#machine[data-state=result]');assert.equal(await page.locator('#machine').getAttribute('data-mode'),null);assert.equal((await snapshot()).world.completedDraws,3);
 // Music flower +2, cooldown, focus selection, no crown selection.
 await seed({...base,world:{completedDraws:2,pending:[]}});await page.locator('[data-memory=music-flowers]').click();assert.equal((await snapshot()).energy.balance,9);await page.locator('[data-memory=music-flowers]').click();assert.equal((await snapshot()).energy.balance,9);assert.equal((await snapshot()).garden.workshop.musicReadyAt,5);await page.locator('[data-memory=wish-gems]').click();assert.equal(await page.locator('[data-treasure="75-starlight-crown"] .place-treasure').count(),0);await page.locator('[data-treasure="zizi-owl"] .place-treasure').click();assert.equal((await snapshot()).garden.workshop.focusRemaining,5);await page.reload();assert.equal((await snapshot()).garden.workshop.focusRemaining,5);
 // Persisted weather due is not rerolled; queued visitors take priority; day switch coalesces.
 await seed({...base,world:{completedDraws:2,pending:[]},garden:{slots:[],environment:{weatherDueDraw:3,dayMs:179500}}});await capture();await page.waitForFunction(()=>document.body.dataset.time==='night');await page.keyboard.press('Space');await page.waitForSelector('#machine[data-state=result]');await page.waitForSelector('#weather-play:not([hidden])');assert.equal((await snapshot()).garden.environment.weatherDueDraw,3);await page.locator('#weather-play-close').click();const due=(await snapshot()).garden.environment.weatherDueDraw;assert.ok(due>=6&&due<=9);await page.reload();assert.equal((await snapshot()).garden.environment.weatherDueDraw,due);
 await seed({...base,world:{completedDraws:10,pending:[{kind:'upgrade',level:'rainbow'}]},garden:{slots:[],environment:{weatherDueDraw:10,dayMs:179900}}});await page.keyboard.press('Space');await page.waitForSelector('#world-dialog.acted');assert.ok(await page.locator('#weather-play').isHidden());await page.locator('#continue-world').click();await page.waitForFunction(()=>document.body.dataset.season==='summer');await page.waitForSelector('#weather-play:not([hidden])');
 // Actual damage, reload after impact, recovery and click repair. No pending gift duplicates.
 for(const [enemy,hits,threshold]of[['witch',4,2],['bat',3,1],['rock',6,3],['dragon',8,2]]){
  await seed({...base,world:{...base.world,completedDraws:60,pending:[{kind:'witch',opponent:enemy,manual:true,hits:0,giftId:'cloud-dolphin'}]}});await page.waitForSelector('#witch-stage[data-action=ready]');for(let i=0;i<threshold;i++)await hit();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('75-magic-machine:v1')).world.pending[0].damage.attacks===1);let state=await snapshot();if(enemy==='witch')assert.equal(state.energy.balance,6);if(enemy==='bat')assert.equal(state.world.pending[0].damage.trapped,'cloud-dolphin');if(['rock','dragon'].includes(enemy))assert.ok(state.garden.workshop.broken.includes('music-flowers'));
  await page.reload();await page.waitForSelector('#witch-stage[data-action=ready]');assert.equal((await snapshot()).world.pending[0].damage.attacks,1);if(enemy==='witch')assert.equal((await snapshot()).energy.balance,6);await win();state=await snapshot();assert.equal(state.energy.balance,7);assert.equal(state.inventory['cloud-dolphin'],2);assert.equal(state.history.length,1);assert.equal(state.garden.workshop.challengeReadyAt,63);assert.equal(await page.locator('.treasure-trapped').count(),0);if(['rock','dragon'].includes(enemy)){assert.ok(state.garden.workshop.broken.includes('music-flowers'));await page.locator('[data-memory=music-flowers]').click();assert.ok(!(await snapshot()).garden.workshop.broken.includes('music-flowers'));assert.equal((await snapshot()).energy.balance,7);}
  await page.reload();assert.equal((await snapshot()).inventory['cloud-dolphin'],2);
 }
 // Mother intercepts energy before flag; flag intercepts traps; active challenge respects cooldown.
 await seed({...base,inventory:{...base.inventory,'loving-mom':1},garden:{...base.garden,slots:['loving-mom'],workshop:{guardWon:true}},world:{...base.world,pending:[{kind:'witch',opponent:'witch',hits:0,giftId:'cloud-dolphin'}]}});await page.waitForFunction(()=>document.getElementById('witch-hit-count').textContent==='1 / 4');await hit();await page.waitForFunction(()=>document.getElementById('witch-stage').classList.contains('guardian-shield'));assert.equal((await snapshot()).energy.balance,7);assert.equal((await snapshot()).garden.workshop.flagReadyAt,0);
 await seed({...base,garden:{...base.garden,workshop:{guardWon:true}},world:{...base.world,pending:[{kind:'witch',opponent:'bat',hits:0,giftId:'cloud-dolphin'}]}});await page.waitForSelector('#witch-stage[data-action=ready]');await hit();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('75-magic-machine:v1')).world.pending[0].damage.attacks===1);assert.equal((await snapshot()).world.pending[0].damage.trapped,null);assert.equal((await snapshot()).garden.workshop.flagReadyAt,43);
 await seed({...base,garden:{...base.garden,workshop:{challengeReadyAt:41}}});await page.locator('.garden-challenge-menu summary').click();assert.ok(await page.locator('[data-challenge=bat]').isDisabled());assert.ok(await page.locator('[data-challenge=dragon]').isDisabled());await seed(base);await page.locator('.garden-challenge-menu summary').click();await page.locator('[data-challenge=bat]').click();await page.waitForSelector('#witch-stage[data-action=intro]');assert.equal((await snapshot()).energy.balance,7);assert.equal((await snapshot()).world.completedDraws,40);assert.equal((await snapshot()).world.pending[0].manual,true);
 assert.deepEqual(errors,[]);console.log('Mechanics: in-machine fusion/mode/Space, facilities, weather cadence and upgrade priority, all four destructive attacks with refresh/recovery, mother/flag priority and manual cooldown.');
}finally{await browser.close();}
